# docker-compose-dev.yml

services:
  db:
    image: postgres:13
    environment:
      TZ: Asia/Tehran
      POSTGRES_USER: tuttyuser
      POSTGRES_PASSWORD: tuttypassword
      POSTGRES_DB: tuttydb
    volumes:
      - ../captioni_data/db_data:/var/lib/postgresql/data
  nginx:
    image: nginx:latest
    depends_on:
      - frontend
      - backend
    ports:
      - "${NGINX_PORT}:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro

  redis:
    image: redis:7-alpine
    environment:
      TZ: Asia/Tehran

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile.dev
    environment:
      TZ: Asia/Tehran
      BASE_URL: http://test.tootty.com:81
      APP_ENV: development
      
    env_file:
      - .env.dev

    restart: unless-stopped
    volumes:
      - ./backend:/app
      - ../captioni_data/uploads_data:/app/uploads
      
    depends_on:
      - db
      - redis
    dns:
      - 8.8.8.8
      - 8.8.4.4

    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 60s
      timeout: 20s
      retries: 3

  celery_worker:
    build:
      context: ./backend
    environment:
      TZ: Asia/Tehran
    command: celery -A celery_config worker -l info --concurrency=5
    volumes:
      - ./backend:/app
      - ../captioni_data/uploads_data:/app/uploads
    depends_on:
      - backend
      - redis
    env_file:
      - .env.dev

  frontend:
    build:
      context: ./frontend
      args:
        NEXT_PUBLIC_API_URL: /api
        NEXT_PUBLIC_GOOGLE_CLIENT_ID: 912769466891-b6rbvu0ep9lugk2dk3htrokgsae0oqo2.apps.googleusercontent.com

    environment:
      TZ: Asia/Tehran
      NEXT_PUBLIC_API_URL: /api
      NEXT_PUBLIC_GOOGLE_CLIENT_ID: 912769466891-b6rbvu0ep9lugk2dk3htrokgsae0oqo2.apps.googleusercontent.com
      WATCHPACK_POLLING: "true"
    volumes:
      - ./frontend:/app
      - /app/node_modules
      - /app/.next
    command: ${CMD:-"npm start"}
    depends_on:
      - backend
      - redis
